### ISSUE TITLE
Scratch API broken.

### ISSUE THREAD

**Issue by herronjo** [trumank/scratch-api#10]
Recently, the Scratch Team has throttled requests to one request every 1.5 seconds in anticipation for hour-of-code. As of right now, this module does not support that throttling. It would be greatly appreciated if that was fixed, or if you at least gave me some instructions on how to adjust the delay myself.

**Comment by liam4** [comment]
> Recently, the Scratch Team has throttled requests to one request every 1.5 seconds in anticipation for hour-of-code.

This is just for the cloud, right?

**Comment by herronjo** [comment]
Yes, just one request to the cloud every 1.5 seconds.

**Comment by trumank** [comment]
I had to implement the HTTP fallback (ew) for the cloud API because the TCP version is not functional at this time. But this at least makes cloud variables usable again.
