### ISSUE TITLE
Update for newcloud

### ISSUE THREAD

**Issue by herronjo** [trumank/scratch-api#12]
Scratch recently released a feature called “newcloud”, and for a while, it was an optional thing that you’d put at the end of the url to use the new cloud system (?newcloud). Now, with the update to the messages system, it seems they have shut down the old cloud server and replaced it with newcloud as the default. This system uses websockets (and I think TCP), and as far as I know, has no easy way to get cloud variables through an API like you used to.

**Comment by trumank** [comment]
Thanks for letting me know. I've updated the package to use the new protocol.

**Comment by herronjo** [comment]
Thanks. Do you think it would be wise to implement some method of detecting when the cloud is in HTTP fallback so the hour of code problems don’t happen again?
