### ISSUE TITLE
Cloud Not Working

### ISSUE THREAD

**Issue by csf30816** [trumank/scratch-api#16]
Two days ago I made code that see's when the cloud is set and then set's variables based on that. I tested it  and it worked and it worked upto today. I found out it is not reading the set variables. It gave me an error but I did not copy it so next time I will. But maybe Scratch changed it's cloud again?

**Comment by towerofnix** [comment]
I don't know if we're having the *same* troubles, but it also isn't/wasn't working here, as of yesterday. Note that when I tried to set a variable, I got a 502 Bad Gateway error, but only 20-30s after I called `.set`. No cloud data was changed online.

**Comment by TotallyOriginal** [comment]
Oh man I'm so glad someone else is having this issue.  I spent all day thinking it was a problem on my end.  I seem to get a 504 error from timing out after creating a cloud session.

**Comment by trumank** [comment]
Fixed by 750dae5f26b64e50f02e8b100b4c6e9f1a4c65d3
