### ISSUE TITLE
Commenting on studios not working

### ISSUE THREAD

**Issue by encloinc** [trumank/scratch-api#17]
var Scratch = require('scratch-api')
Scratch.UserSession.load(function(err, user) {
  if (err) return console.error(err);
  user.addComment({"studio":"4028545", "content":"hello!"},
  function(err, res) {
    if (err) return console.error(err);
    console.log('Done!');
  });
});

This isnt posting anything. What gives?

**Comment by trumank** [comment]
Works for me?

**Comment by encloinc** [comment]
hmm, maybe im doing something wrong? Thats literally all my code

**Comment by towerofnix** [comment]
@encloinc It looks like it's working now? I'm seeing two "hello!" comments from you, from within the last four minutes. Is this resolved?

**Comment by encloinc** [comment]
yeah, however the replyto isnt? im feeding it a username. parent is working though

**Comment by encloinc** [comment]
@towerofnix

**Comment by towerofnix** [comment]
@encloinc It's the ID returned from the API, yeah.

**Comment by encloinc** [comment]
Im having problems with it. The comment is posting an empty @ , like its replying but thats it

**Comment by encloinc** [comment]
I think it changed to commentee_id

**Comment by towerofnix** [comment]
Mind sharing your code, so I can test it and help figure out the problem?

**Comment by encloinc** [comment]
Figured this out thanks man 👍

**Comment by joker314** [comment]
I think it's fair to say that the documentation is a little unclear, because right after saying 'user ID' it goes on to write '(@username ...)'.

Maybe we could re-write that documentation to explain that it's a numeric ID, and even add some validation so that an error is thrown if you don't do this right.

**Comment by encloinc** [comment]
That would be great!
