### ISSUE TITLE
Let caller of UserSession.load choose what to use as session file

### ISSUE THREAD

**Issue by towerofnix** [trumank/scratch-api#18]
Currently, the session file is always determined according to the constant `SESSION_FILE` (which is equivalent to `.scratchSession`). It would be nice if you could pass to `UserSession.load` what file to use in place of `.scratchSession`.

**Comment by trumank** [comment]
Loading from a file was intended for convenient testing via CLI. If more complicated session management is needed, it should be implemented externally by the user.
