### ISSUE TITLE
"cb is not a function"

### ISSUE THREAD

**Issue by Navull** [trumank/scratch-api#19]
I keep getting the error "cb is not a function"
It happens when I use any function for example:
`Scratch.getProject(215019012,"");`
Am I doing something wrong?

**Comment by towerofnix** [comment]
@Navull Yeah, you've got just one thing mistaken -- instead of passing a string like `""`, you need to pass a callback function, like this:

```js
Scratch.getProject(215019012, function(err, project) {
  if (err) {
    console.error('Error!', err);
    return;
  }
  console.log(project);
});
```

I recommend you look up an article on how Node.js callbacks work, it should help explain :)
