### ISSUE TITLE
Cant send sequential messages

### ISSUE THREAD

**Issue by encloinc** [trumank/scratch-api#20]
The api wont let me send sequential messages. Im replying to a comment first and then im posting a new message elswhere (on another profile), however for some reason this isnt working.

**Comment by joker314** [comment]
It might be that you are encountering rate limiting (Scratch ignoring too many requests in a shrot amount of time to protect against some types of attacks). Could you share some of your code for us to test, and try adding a shrot delay before sending the second comment.

Is your account labelled as a 'New Scratcher'? The rate limiting for those is much higher.

**Comment by encloinc** [comment]
oh that might be it yeah im using a new scratcher

**Comment by joker314** [comment]
Sounds about right then! Just to check, was there an error passed to the callback function, and if so, what was it?

```
user.addComment(options_object, console.error)
```

with `options_object` probably being something like `{parent: "...", replyto: "...", ...}`

**Comment by encloinc** [comment]
No there wasnt any errors, its super weird.

**Comment by joker314** [comment]
Ah, yeah, it looks like only issues with the fetching of the data become errors, the status code of the response is not checked. I think there should be an error if the status code is not 200m and that would've probably made this less confusing.

Nonetheless, this does look like a rate-limiting issue, so just try to spread your requests out a little and this issue should be avoided. Alternatively, get a 'Scratcher' status account, but still try not to spam the Scratch servers! :slightly_smiling_face:

**Comment by encloinc** [comment]
It only sent 2 requests, its just that they were very close to eachother :)
