### ISSUE TITLE
Scratch 3 Support

### ISSUE THREAD

**Issue by AwesomeKalin** [trumank/scratch-api#21]
When will you release support for Scratch 3?

**Comment by e-porter** [comment]
Does it not work with Scratch 3?

**Comment by e-porter** [comment]
I'll check this out later, and if it doesn't work I'll see if I can make a pr.

**Comment by TropicSapling** [comment]
My friend has made this rewrite for Scratch 3.0: https://github.com/mytopdog/node-scratch-client
Haven't tested too much of it yet, but logging in, getting project data and creating comments are some of the things I know work so far.

**Comment by AwesomeKalin** [comment]
Great

**Comment by trumank** [comment]
I have no plans to add features to this lib myself (due to lack of time and no personal need), but I welcome changes/additions by from others if they find them useful.
