### ISSUE TITLE
Cannot enter password

### ISSUE THREAD

**Issue by Ryangeorge-ctrl** [trumank/scratch-api#36]
Code:

var Scratch = require("scratch-api");
const fetch = import("node-fetch")

Scratch.UserSession.load(function(err, user) {
    if (err) return console.error(err);
    user.cloudSession(615477858, function(err, cloud) {
        if (err) return console.error(err);
        function timeout() {
            setTimeout(function () {
                fetch('https://api.scratch.mit.edu/users/Reologist/projects/615477858')
                    .then(res => res.json())
                    .then(data => {
                        cloud.set('☁ loves', data.stats.loves)
                        cloud.set('☁ favourites', data.stats.favorites)
                        cloud.set('☁ comments', data.stats.comments)
                    })
                timeout();
            }, 5000);
        }
        timeout()
    });
});

???

**Comment by Ryangeorge-ctrl** [comment]
it just doesnt let me type it

**Comment by gohoski** [comment]
Are you sure that it's not letting you type anything? If the password that you are typing doesn't show up in the console, then no worries: it should be like that.
