### ISSUE TITLE
Is there any way to programatically detect who made the last change to a variable?

### ISSUE THREAD

**Issue by Felizolinha** [trumank/scratch-api#4]
This functionality is almost a must-have to detect people messing with your variables :package:

**Comment by trumank** [comment]
The server never sends information telling which user sets a variable so it is impossible without scanning. https://scratch.mit.edu/cloudmonitor/, which I may think about doing.

**Comment by trumank** [comment]
As of right now, Scratch doesn't have a good way to do this so I'm closing this issue.

**Comment by bjskistad** [comment]
@trumank wouldn't it be relatively easy to check the cloud monitor of a project? Or is there not a json API for it?

**Comment by trumank** [comment]
It would have to parse the html and verify that the message matches the user and with truncated results in the cloud monitor and latency issues, the result would be gross and unreliable.

**Comment by bjskistad** [comment]
I see. Well, is the ST open to making a new API?
