### ISSUE TITLE
More Examples / Documentation?

### ISSUE THREAD

**Issue by Arinerron** [trumank/scratch-api#5]
I suggest you add more examples. Stuff like:
- Change cloud variable
- Clear cloud variable
- Clear backpack
- Get a list of all your followers
- Unfollow everyone you are currently following
- Get a list of all the Scratch users / as many as possible
- Comment on a person's profile
- Create a new project

Some of those may not have support in your library, and if not, please add it? :P 
Also, you should add more documentation for:
- How to setup a NodeJS environment for this
- More stuff :package:

**Comment by Jonathan50** [comment]
There's already documentation for all the functions and examples to get started, so I don't think this is necessary,

And you should probably know how to set up a Node.JS 'environment'. It's not that hard

**Comment by Arinerron** [comment]
@Jonathan50 ...
Okay, there's documentation. Not enough. I think there should be more, regardless of how 'necessary' it is.
I do, but quite a few people don't; my friend didn't. Why not have documentation for that? It would make people like him be able to use it with more ease (same with the other documentation). Just sayin'...

**Comment by Jonathan50** [comment]
> Why not have documentation for that?

Because _Node.JS_ has documentation for _Node.js_.  
And _every function_ (AFIAK) is documented. (you should probably be able to figure out any other functions from the prototype).

**Comment by Arinerron** [comment]
@Jonathan50 Mk, I guess I concede. Node.js does have documentation, you're right. And you *are* also right in that every function is documented. I just figured it'd be cooler if it had more examples.

P.S. AFIAK? Ya mean AFAIK? :stuck_out_tongue_winking_eye:

**Comment by Jonathan50** [comment]
> AFIAK? Ya mean AFAIK?

yes oops ft

**Comment by trumank** [comment]
Correct me if I am wrong, but I think I documented everything thoroughly enough. However, instructions for setting up node.js are out of the scope of this project.
