### ISSUE TITLE
Cloud.get returning undefined

### ISSUE THREAD

**Issue by scratchyone** [trumank/scratch-api#6]
I'm trying to use cloud.get, and it always returns undefined, even though I know I have the correct name. I have even copied it from the cloud log (including the cloud symbol), but it never works.

**Comment by Arinerron** [comment]
You tried it without the cloud symbol, correct?

**Comment by scratchyone** [comment]
I don't remember. It seems like the callback was being called before it was ready, because after adding a setTimeout, it works.

**Comment by scratchyone** [comment]
@Arinerron Now that it's working, when I change a var, it changes for the server, but not on scratch.

**Comment by Arinerron** [comment]
@scratchyone I know that bug-- I experienced it when I changed cloud data from the same account as in the editor. You have to use an alt account that isn't a New Scratcher to change the cloud data.

**Comment by Jonathan50** [comment]
@Arinerron It's not a bug. And it doesn't matter whether or not it's a new scratcher.

**Comment by Arinerron** [comment]
@Jonathan50

From Wikipedia:
```
A bug is an error, flaw, failure, or fault in a computer program or system that causes it to produce an incorrect or unexpected result or to behave in unintended ways.
```

I meant there was a bug with the software I had written (and he had written). You are right, however, there are better, less ambiguous words that could be used, ex. 'issue'.

**Comment by Arinerron** [comment]
@Jonathan50 Oh, and as for the Scratcher/New Scratcher thing, I was saying you **must** be a Scratcher in order to modify cloud data. Feel free to read here if you don't agree: http://wiki.scratch.mit.edu/wiki/Cloud_Data

**Comment by Jonathan50** [comment]
@Arinerron it's not a bug because it is a restriction imposed by Scratch. Scratch does not allow you to have multiple cloud sessions with the same account.

The New Scratcher restriction is only imposed on the client side. Yes, to use cloud data with the flash player, you need to be a Scratcher, but you don't need to be a Scratcher to change cloud data with scratch-api.

**Comment by Arinerron** [comment]
@Jonathan50 Alright. I'll call it an issue then.
I did not know it is a client side issue, thanks. That makes me happy (I want to be able to use my main account for cloud data, and I thought creating a new account wouldn't work).

**Comment by trumank** [comment]
Seems like there isn't an actual problem here. Just to clarify, Scratch does not allow multiple sessions from the same user to a single project.

**Comment by scratchyone** [comment]
@trumank The account I'm using is a scratcher and I have verified the session, yet cloud.set still doesn't work

**Comment by trumank** [comment]
Did you check the cloud log to see if it was ever set?

**Comment by scratchyone** [comment]
Yep. Nothing was sent.

On Thursday, April 7, 2016, Truman Kilen <notifications@github.com> wrote:

> Did you check the cloud log to see if it was ever set?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/trumank/scratch-api/issues/6#issuecomment-207107003>
>


--

**Comment by trumank** [comment]
What is the code you used and project you are testing?

**Comment by scratchyone** [comment]
```
var Scratch = require('scratch-api');

Scratch.UserSession.create("scratchyone_test", "<snip>", function(err, user) {
	user.verify(function(err,valid) {console.log(err);
	console.log(valid)
	})
  user.cloudSession(104386037, function(err, cloud) {
	  setTimeout(function () {
		  cloud.set(String.fromCharCode(9729)+" get", 0)
		  setInterval(function() {
	  if(cloud.get(String.fromCharCode(9729)+" get")=="1") {
		  temp=cloud.get(String.fromCharCode(9729)+" Username").split("A")
		  //console.log(temp)
		  for(i=1;i<temp.length;i++) {
			  temp[i]=String.fromCharCode(temp[i]);
		  }
		  temp.shift()
		  console.log(temp.join(""))
		  
	  }
		  },500)
	  },1000)
  });
});
```

**Comment by scratchyone** [comment]
https://scratch.mit.edu/projects/104386037/

**Comment by trumank** [comment]
That was weird. The cloud token in https://scratch.mit.edu/projects/<project>/cloud-data.js shifted over one character and started sending the wrong token. It's fixed now.

**Comment by scratchyone** [comment]
Yay! Thanks :smiley:

**Comment by Jonathan50** [comment]
Maybe you should do some regex search in case changes like that happen in the future?

**Comment by Jonathan50** [comment]
\*attempts to log in to @scratchyone on Scratch using password \<snip\>\* jk

**Comment by trumank** [comment]
I think if something is gonna change again, the cloud token is going to move to another API point entirely.
