### ISSUE TITLE
Get CSRF token and sessionid

### ISSUE THREAD

**Issue by scratchyone** [trumank/scratch-api#7]
Sometimes I want to send raw requests to the apis that require a token. Can I get the CSRF and SESSIONID after I start the user session?

**Comment by trumank** [comment]
The CSRF token doesn't matter and scratch-api doesn't use the one provided by Scratch. The session token can be obtained with Scratch.UserSession::sessionId.

**Comment by scratchyone** [comment]
It doesn't matter? What should I do when a request needs a CSRF token?

On Friday, April 22, 2016, Truman Kilen <notifications@github.com> wrote:

> Closed #7 <https://github.com/trumank/scratch-api/issues/7>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/trumank/scratch-api/issues/7#event-637448426>
>


--

**Comment by trumank** [comment]
Send the same string for the cookie as well as in the header and you should be good.

**Comment by scratchyone** [comment]
The header is "X-CSRF-TOKEN" right?

On Friday, April 22, 2016, Truman Kilen <notifications@github.com> wrote:

> Send the same string for the cookie as well as in the header and you
> should be good.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/trumank/scratch-api/issues/7#issuecomment-213361479>
>


--

**Comment by trumank** [comment]
Yes.

https://github.com/trumank/scratch-api/blob/master/scratchapi.js#L17

**Comment by scratchyone** [comment]
Thanks for your help! Scratch-api is amazing!

On Friday, April 22, 2016, Truman Kilen <notifications@github.com> wrote:

> Yes.
>
> https://github.com/trumank/scratch-api/blob/master/scratchapi.js#L17
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/trumank/scratch-api/issues/7#issuecomment-213364438>
>


--

**Comment by trumank** [comment]
Thanks!

**Comment by scratchyone** [comment]
I get an error when I use Scratch.UserSession::sessionId. Node doesn't seem to like the "::"

**Comment by trumank** [comment]
The :: notation means 'a property of an instance of _'. So for the example in the readme, you would use 'user.sessionId' to get the session token.

**Comment by scratchyone** [comment]
Oh! Thanks! The sessionid has qoutes around it. Do I include those?

**Comment by scratchyone** [comment]
```
var Scratch = require('scratch-api');
Scratch.UserSession.load(function(err, user) {
  if (err) return console.error(err);
  sid=user.sessionId
console.log(sid)
var request = require('request');

var options = {
  url: 'https://scratch.mit.edu/site-api/users/followers/drkat123/add/?username=scratchyone_test',

  headers: {
    'Cookie': 'scratchcsrftoken='+sid+'; scratchlanguage=en;',
    'X-CSRFToken': sid,
    'referer': 'https://scratch.mit.edu' // Required by Scratch servers
  }
};

function callback(error, response, body) {
  if (!error && response.statusCode == 200) {
console.log(body)
  }
  request.put(options, callback);
}
});

```

**Comment by scratchyone** [comment]
Like that? It doesn't work

**Comment by trumank** [comment]
This library isn't really meant to be used for "custom" requests. If it's missing a feature you need, add it to the library and send a pull request so I can make it official. It's a lot cleaner adding it inside the library. Just look at the other types of requests for an example of how to do it.

**Comment by Jonathan50** [comment]
> The header is "X-CSRF-TOKEN" right?

No, it's X-CSRFToken (no hyphen)
