### ISSUE TITLE
Does not work with my website

### ISSUE THREAD

**Issue by csf30816** [trumank/scratch-api#9]
See above ^

<hr>

`Uncaught ReferenceError: require is not defined ` appears as an error

**Comment by trumank** [comment]
It must be run in a node.js environment. It cannot run inside of a regular webpage.

**Comment by bjskistad** [comment]
@csf30816 Node.js is not a client side language. To use this API in a form of a website, you would have to create a HTTP or HTTPS server and send whatever you need from the API that way.

Cheers,

**Comment by csf30816** [comment]
OK, thanks

**Comment by Arinerron** [comment]
This is off-topic, but @csf30816, you should make your username @csrf30816 :stuck_out_tongue_winking_eye: 

_...just an security joke..._

**Comment by csf30816** [comment]
lol

_...You have a spelling error: `just an security joke` should be `just a security joke`_

**Comment by Arinerron** [comment]
That was an accident. I'll edit that :P

I actually typed a different italic message, but changed it. I forgot to change the 'an' to' a'.
